### ISSUE TITLE
Ciclo de vida

### ISSUE THREAD

**Issue by ryanfox1985** [OsTheNeo/wizard#2]
La idea es que el componente solo se muestre una vez (la primera vez que arranca), deberia guardar una cache para no mostrarlo una segunda vez.

**Comment by OsTheNeo** [comment]
Se implemente AsyncStorage para el control del ciclo de vida del componente
https://github.com/OsTheNeo/wizard/commit/593c525650f6b641ec226cef6ab532c2cb2b9ebd
