### ISSUE TITLE
Limpiar App.js

### ISSUE THREAD

**Issue by ryanfox1985** [OsTheNeo/wizard#3]
Podrias encapsular el carousel en un componente y dejar limpio el app.js?

**Comment by OsTheNeo** [comment]
- Estilos separados https://github.com/OsTheNeo/wizard/commit/2cca0a749cc6df9ccf8df197a8a47c285754894d
- Orden de los assets https://github.com/OsTheNeo/wizard/commit/99fb2729654a6a6ec8dc186d9df0ecec1d2d9e4b
- Implementación de navegación, separación de la data, componente intro independiente https://github.com/OsTheNeo/wizard/commit/ae201e255e7543559a7c5f94311369936123d702
