### ISSUE TITLE
Bug en el último paso

### ISSUE THREAD

**Issue by ryanfox1985** [OsTheNeo/wizard#4]
Hola,

en el último paso hay un bug, aparece tienes que acabar la última slide para finalizar.
Adjunto capturas:

![Screenshot_20201008-133747_wizard](https://user-images.githubusercontent.com/1152728/95453851-e13db380-096b-11eb-8ee8-36f4f2ef4cfb.png)
![Screenshot_20201008-133752_wizard](https://user-images.githubusercontent.com/1152728/95453856-e3a00d80-096b-11eb-880b-19a4304f4fac.png)

Saludos.

**Comment by OsTheNeo** [comment]
solucionado https://github.com/OsTheNeo/wizard/commit/a2c4d6cdb8184347681280cd306c326cb4a24401
